//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalAzariBDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDealership
    {
        public int DealershipID { get; set; }
        public string DealershipName { get; set; }
        public string DealershipType { get; set; }
        public string DealershipPhone { get; set; }
        public string DealershipAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
