//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalAzariBDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int UserID { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleType { get; set; }
        public string Department { get; set; }
        public Nullable<int> SalesActivityH { get; set; }
        public Nullable<int> SalesActivityD { get; set; }
        public Nullable<int> SalesCall { get; set; }
        public Nullable<int> SalesContact { get; set; }
        public Nullable<int> SalesAppt { get; set; }
        public Nullable<int> SeviceActivityH { get; set; }
        public Nullable<int> SeviceActivityD { get; set; }
        public Nullable<int> SeviceCall { get; set; }
        public Nullable<int> SeviceContact { get; set; }
        public Nullable<int> SeviceAppt { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
